# Generated by Django 4.1.2 on 2023-01-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="showing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filmtitle", models.CharField(max_length=100)),
                ("agerating", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=50)),
            ],
        ),
    ]
